name: Extensions
on:
  workflow_call:
jobs:
  jupyterlab:
    env:
      DOCKER: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - run: just jupyterlab install
      - run: just jupyterlab validate
      - run: just jupyterlab test
